### ISSUE TITLE
Can not compile editor project...

### ISSUE THREAD

**Issue by moebiussurfing** [kaazedev/imgui-editor#1]
**Describe the bug**
Getting errors on compile in VS.

**To Reproduce**
1. F5

**Screenshots**
![image](https://user-images.githubusercontent.com/2106149/215519562-205d2866-b4c2-4299-a912-3cc77be92117.png)

**Desktop (please complete the following information):**
 - OS: Windows VS 2022
**Additional context**
I tried with the projects from the root folder and \imgui-editor\imgui-editor

**Comment by pearleascent** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by moebiussurfing** [comment]
fixed deleting c:/imgui.tech

**Comment by pearleascent** [comment]
> fixed deleting c:/imgui.tech there were a no named .json file that made crash the app

Thanks for the information, I'll take a look and try to fix it soon.

**Comment by moebiussurfing** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=6812

ok. 

I had to add #include <string> into
imgui-editor\dependencies\modals\modals.hpp

but don't know how to fix that:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: '../../dependencies/imgui/imgui.h': No such file or directory (compiling source file src\workspace\widgets\checkboxSettings.cpp)	imgui-editor	D:\_CODE\_C\imgui-editor\imgui-editor\src\workspace\widgets\checkboxSettings.hpp	5	

imgui.h is there and relative path looks its well..

**Comment by moebiussurfing** [comment]
ok. thanks.
now it compiles. but required two modifications:

![image](https://user-images.githubusercontent.com/2106149/215537862-bf095613-2039-4e75-a45a-f6510e4137b5.png)
![image](https://user-images.githubusercontent.com/2106149/215537931-dece6afb-4c74-4809-965a-266bc8337681.png)
