### ISSUE TITLE
Docs link is broken in the readme

### ISSUE THREAD

**Issue by x1nixmzeng** [kaazedev/imgui-editor#13]
## Describe the bug
Unable to visit the link to the docs

### Steps to reproduce
Follow the docs link in the readme

### Expected behavior
The docs sources or pre-rendered sources are available

### Environment
 - OS: N/A
 - Browser link from the project github

### Additional context
The broken url points to https://github.com/kaazedev/imgui-editor/docs

**Comment by kaazedev** [comment]
Fixed, docs will be available soon
