### ISSUE TITLE
good malware

### ISSUE THREAD

**Issue by blluettw** [kaazedev/imgui-editor#15]
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

**Comment by GLX-ILLUSION** [comment]
good malware in release file don't download release file guys

**Comment by GLX-ILLUSION** [comment]
![image](https://github.com/kaazedev/imgui-editor/assets/76027489/117ce1a0-3fe1-44c0-b866-6d5f6db03bd7)

**Comment by kaazedev** [comment]
![image](https://github.com/kaazedev/imgui-editor/assets/113010734/c0985348-f946-465b-af44-82b34cca5b7c)

download releases source and compile yourself, and you will get same application
