### ISSUE TITLE
Compilation issues regarding MinGW

### ISSUE THREAD

**Issue by Ena-Shepherd** [kaazedev/imgui-editor#16]
## Describe the bug
Hello, building on MinGW doesn't work due to the project using Unicode.
it leads to conversion type errors such as the compiler refusing to convert `char *` to `LPSTR`.

### Steps to reproduce
Build using Msys2 MinGW-64 :
- `mkdir build && cd build`
    - `cmake .. -GNinja -DCMAKE_CXX_COMPILER="clang++"`
    - `cmake .. -GNinja -DCMAKE_CXX_COMPILER="g++"`
    - `cmake .. -G "MinGW Makefiles"`
 - build
     - `ninja`
     - `mingw32-make`
  - log : `cannot convert 'const char*' to 'LPCWSTR {aka const wchar_t*}` multiple times in the source and header files

### Expected behavior
The project builds normally

### Environment
 - OS: Windows Msys2 MinGW-64
 
 Thank you for your patience, have a good day 👍

**Comment by kaazedev** [comment]
Most likely fixed, please clone the repository again and try to build.
