### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by JackRichardson666** [kaazedev/imgui-editor#2]
Release/Win32
VSC 2022
DirectX installed

![изображение](https://user-images.githubusercontent.com/64367044/219371273-be4465fa-6561-4447-bcac-c817de2dcce4.png)

**Comment by pearleascent** [comment]
sdk version?

**Comment by JackRichardson666** [comment]
> sdk version?

last (just download from repo)

**Comment by pearleascent** [comment]
sorry, misunderstanding, i meant Windows SDK

**Comment by slipybit** [comment]
> sorry, misunderstanding, i meant Windows SDK

10.0.20348.0

**Comment by JackRichardson666** [comment]
> sorry, misunderstanding, i meant Windows SDK

10.0.20348.0

**Comment by ChivenZhang** [comment]
![image](https://user-images.githubusercontent.com/48938612/223233937-cda611be-fde6-4dce-b860-f70976ab0c85.png)

DXSDK is not recommanded in newest os version. Anyway I have run the project well.
